---
logoutput:                     &logoutput                     true

# create 2 managed servers and assign them to the machines
managed_servers_instances:
   - clusterOne:
      global_parameters:
         log_output:           *logoutput
         weblogic_type:        "server"
         script:               'createServer.py'
      wlsServer1_node1:
         weblogic_object_name: "wlsServer1"
         params:
            - "javaArguments    = '-XX:PermSize=256m -XX:MaxPermSize=256m -Xms752m -Xmx752m -Dweblogic.Stdout=/data/logs/wlsServer1.out -Dweblogic.Stderr=/data/logs/wlsServer1_err.out'"
            - "wlsServerName    = 'wlsServer1'"
            - "machineName      = 'Node1'"
            - "listenAddress    = 8001"
            - "nodeMgrLogDir    = '/data/logs'"
      wlsServer2_node2:
         weblogic_object_name: "wlsServer2"
         params:
            - "javaArguments    = '-XX:PermSize=256m -XX:MaxPermSize=256m -Xms752m -Xmx752m -Dweblogic.Stdout=/data/logs/wlsServer2.out -Dweblogic.Stderr=/data/logs/wlsServer2_err.out'"
            - "wlsServerName    = 'wlsServer2'"
            - "machineName      = 'Node2'"
            - "listenAddress    = 8001"
            - "nodeMgrLogDir    = '/data/logs'"

# create cluster and assign the managed servers
cluster_instances:
   - clusterOne:
      global_parameters:
         log_output:           *logoutput
         weblogic_type:        "cluster"
         script:               'createCluster.py'
      cluster_web:
         weblogic_object_name: "WebCluster"
         params:
            - "clusterName      = 'WebCluster'"
            - "clusterNodes     = 'wlsServer1,wlsServer2'"


# create jms servers with a server,file persistence target
jms_servers_instances:
   - clusterOne:
      global_parameters:
         log_output:           *logoutput
         weblogic_type:        "jmsserver"
         script:               'createJmsServer.py'
      jmsServerNode1:
         weblogic_object_name: "jmsServer1"
         params:
            - "target           = 'wlsServer1'"
            - "targetType       = 'Server'"
            - "jmsServerName    = 'jmsServer1'"
      jmsServerNode2:
         weblogic_object_name: "jmsServer2"
         params:
            - "target           = 'wlsServer2'"
            - "targetType       = 'Server'"
            - "jmsServerName    = 'jmsServer2'"

#
# create jms module for cluster 
jms_module_instances:
   - clusterOne:
      global_parameters:
         log_output:           *logoutput
         weblogic_type:        "jmsmodule"
         script:               'createJmsModule.py'
      jmsClusterModule:
         weblogic_object_name: "jmsClusterModule"
         params:
            - "target           = 'WebCluster'"
            - "targetType       = 'Cluster'"
            - "jmsModuleName    = 'jmsClusterModule'"

# create jms subdeployment for the jms module 
jms_module_subdeployments_instances:
   - clusterOne:
      global_parameters:
         log_output:           *logoutput
         weblogic_type:        "jmssubdeployment"
         script:               'createJmsSubDeployment.py'
      SubDeploymentWLSforJmsModule:
         weblogic_object_name: "jmsClusterModule/wlsServers"
         params:
            - "target           = 'WebCluster'"
            - "targetType       = 'Cluster'"
            - "subName          = 'wlsServers'"
            - "jmsModuleName    = 'jmsClusterModule'"
      SubDeploymentJMSforJmsModule:
         weblogic_object_name: "jmsClusterModule/jmsServers"
         params:
            - "target           = 'jmsServer1,jmsServer2'"
            - "targetType       = 'JMSServer'"
            - "subName          = 'jmsServers'"
            - "jmsModuleName    = 'jmsClusterModule'"

# create jms quotas for the jms module 
jms_module_quotas_instances:
   - clusterOne:
      global_parameters:
         log_output:           *logoutput
         weblogic_type:        "jmsquota"
         script:               'createJmsQuota.py'
      QuotaBigforJmsModule:
         weblogic_object_name: "jmsClusterModule/QuotaBig"
         params:
            - "jmsQuotaName     = 'QuotaBig'"
            - "bytesMaximum     = 9223372036854775807"
            - "messagesMaximum  = 9223372036854775807"
            - "jmsModuleName    = 'jmsClusterModule'"
            - "shared           = false"
            - "policy           = 'FIFO'"
      QuotaLowforJmsModule:
         weblogic_object_name: "jmsClusterModule/QuotaLow"
         params:
            - "jmsQuotaName     = 'QuotaLow'"
            - "bytesMaximum     = 10000000000"
            - "messagesMaximum  = 10000"
            - "jmsModuleName    = 'jmsClusterModule'"
            - "shared           = false"
            - "policy           = 'FIFO'"

# create jms connection factory for jms module  
jms_module_cf_instances:
   - clusterOne:
      global_parameters:
         log_output:           *logoutput
         weblogic_type:        "jmsobject"
         script:               'createJmsConnectionFactory.py'
      createJmsConnectionFactoryforJmsModule:
         weblogic_object_name: "cf"
         params:
            - "subDeploymentName = 'wlsServers'"
            - "jmsModuleName     = 'jmsClusterModule'"
            - "cfName            = 'cf'"
            - "cfJNDIName        = 'jms/cf'"
            - "transacted        = 'false'"
            - "timeout           = 'xxxx'"

jms_module_jms_errors_instances:
   - clusterOne:
      global_parameters:
         log_output:           *logoutput
         weblogic_type:        "jmsobject"
         script:               'createJmsQueueOrTopic.py'
      createJmsErrorQueueforJmsModule:
         weblogic_object_name: "ErrorQueue"
         params:
            - "subDeploymentName = 'jmsServers'"
            - "jmsModuleName     = 'jmsClusterModule'"
            - "jmsName           = 'ErrorQueue'"
            - "jmsJNDIName       = 'jms/ErrorQueue'"
            - "jmsType           = 'queue'"
            - "distributed       = 'true'"
            - "balancingPolicy   = 'Round-Robin'"
            - "useRedirect       = 'false'"
            - "limit             = 'xxxxx'"
            - "policy            = 'xxxxx'"
            - "errorObject       = 'xxxxx'"

# create jms objects for jms module  
jms_module_jms_instances:
   - clusterOne:
      global_parameters:
         log_output:           *logoutput
         weblogic_type:        "jmsobject"
         script:               'createJmsQueueOrTopic.py'
         params:
            - "subDeploymentName = 'jmsServers'"
            - "jmsModuleName     = 'jmsClusterModule'"
            - "distributed       = 'true'"
            - "balancingPolicy   = 'Round-Robin'"
            - "useRedirect       = 'true'"
            - "limit             = '3'"
            - "policy            = 'Redirect'"
            - "errorObject       = 'ErrorQueue'"
      createJmsQueueforJmsModule:
         weblogic_object_name: "Queue1"
         params:
            - "jmsType           = 'queue'"
            - "jmsName           = 'Queue1'"
            - "jmsJNDIName       = 'jms/Queue1'"
      createJmsTopicforJmsModule:
         weblogic_object_name: "Topic1"
         params:
            - "jmsType           = 'topic'"
            - "jmsName           = 'Topic1'"
            - "jmsJNDIName       = 'jms/Topic1'"
